name: deploy

on:
  push:
    # branches: main

jobs:
  deploy-book:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Java JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
            java-version: '1.8' # The JDK version to make available on the path.
            java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
            architecture: x64 # (x64 or x86) - defaults to x64
    - name: Install book requirements
      run: |
        pip install -r requirements.txt
        pip install jupyter-book
        sudo apt install -y --no-install-recommends graphviz
    - name: Install Spark
      run: |
        sudo apt install -y --no-install-recommends tar
        wget https://dlcdn.apache.org/spark/spark-3.3.1/spark-3.3.1-bin-hadoop3.tgz
        tar -xzf spark-3.3.1-bin-hadoop3.tgz
        echo "SPARK_HOME=$PWD/spark-3.3.1-bin-hadoop3" >> $GITHUB_ENV
    - name: Set environment variable for Spark
      run: |
        echo "$SPARK_HOME/bin:$JAVA_HOME/jre/bin" >> $GITHUB_PATH
        echo "PYTHONPATH=$SPARK_HOME/python:$PYTHONPATH" >> $GITHUB_ENV
        echo "PYPSARK_PYTHON=python" >> $GITHUB_ENV
    - name: Build book
      run: |
        jupyter-book build book
    # Deploy html to gh-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./book/_build/html
        publish_branch: gh-pages
